apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: vulnerabilitydemo-service
spec:
  selector:
    app: pacman-api-vulnerability
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8085 # The port exposed by the service
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: vulnerabilitydemo-deployment
spec:
  selector:
    matchLabels:
      app: pacman-api-vulnerability
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: pacman-api-vulnerability
    spec:
      containers:
        - name: pacman-api-vulnerability
          image: vulnerabilityapi:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
